"""Agent Enricher — Data enrichment between pipeline stages.

Enhances raw data with additional context from multiple AI providers.
Adds metadata, cross-references, and quality scores to pipeline data.
"""

from __future__ import annotations

import time
from typing import Any

from rich.console import Console

from src.pipeline_engine import StepResult, StepStatus
from src.services.lm_cluster import query_lm, query_ollama
from src.airia_bridge import bridge
from src import database as db

console = Console()


async def enrich_with_summary(run_id: str, data: Any, context: str = "") -> StepResult:
    """Enrich data with an AI-generated summary."""
    t0 = time.monotonic()
    console.print("[bold magenta]Agent Enricher[/] generating summary...")

    prompt = f"Resume de maniere concise en francais les donnees suivantes:\n{str(data)[:2000]}"
    if context:
        prompt = f"Contexte: {context}\n\n{prompt}"

    summary = None
    model_used = ""

    # Try M1 first (local, fast)
    result = await query_lm(prompt, "M1", system="Tu es un analyste expert. Resume en 3 phrases maximum.")
    if result.get("ok"):
        summary = result["content"]
        model_used = result.get("model", "M1")
    else:
        # Try Ollama
        result = await query_ollama(prompt, "OL1", system="Resume en 3 phrases.")
        if result.get("ok"):
            summary = result["content"]
            model_used = result.get("model", "OL1")
        elif bridge.is_available:
            # Try Airia
            try:
                airia_result = await bridge.query("market_intelligence", prompt)
                if airia_result:
                    summary = str(airia_result)[:500]
                    model_used = "Airia"
            except Exception:
                pass

    latency = (time.monotonic() - t0) * 1000

    if summary:
        enriched = {
            "original": data,
            "summary": summary,
            "model_used": model_used,
            "enriched_at": time.time(),
        }

        db.save_audit(
            run_id, "enrichment", "enricher",
            output_summary=f"Summary generated by {model_used} ({len(summary)} chars)",
            model_used=model_used,
            latency_ms=latency,
        )

        console.print(f"[green]Enricher done[/] — summary by {model_used} in {int(latency)}ms")

        return StepResult(
            step_name="enrichment",
            status=StepStatus.SUCCESS,
            data=enriched,
            confidence=85,
            agent_used="enricher",
            model_used=model_used,
            latency_ms=latency,
        )

    return StepResult(
        step_name="enrichment",
        status=StepStatus.FAILED,
        error="All enrichment providers failed",
        agent_used="enricher",
        latency_ms=latency,
    )


async def enrich_with_metadata(run_id: str, data: Any) -> StepResult:
    """Add metadata tags to data (no AI needed)."""
    t0 = time.monotonic()
    console.print("[bold magenta]Agent Enricher[/] adding metadata...")

    metadata = {
        "run_id": run_id,
        "timestamp": time.time(),
        "data_type": type(data).__name__,
        "data_size": len(str(data)),
    }

    if isinstance(data, list):
        metadata["item_count"] = len(data)
    elif isinstance(data, dict):
        metadata["key_count"] = len(data)

    enriched = {
        "data": data,
        "metadata": metadata,
    }

    latency = (time.monotonic() - t0) * 1000

    console.print(f"[green]Enricher metadata done[/] — {len(metadata)} tags in {int(latency)}ms")

    return StepResult(
        step_name="metadata_enrichment",
        status=StepStatus.SUCCESS,
        data=enriched,
        confidence=100,
        agent_used="enricher",
        latency_ms=latency,
    )


async def run(run_id: str, data: Any, mode: str = "summary") -> StepResult:
    """Execute Agent Enricher: add value to pipeline data."""
    if mode == "metadata":
        return await enrich_with_metadata(run_id, data)
    return await enrich_with_summary(run_id, data)
